[package]
name = "cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "veloura"
path = "src/main.rs"

[dependencies]
application.workspace = true
domain.workspace = true
media.workspace = true
plugin-host.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile.workspace = true
database.workspace = true
zip.workspace = true
